name: Chai
options:
  bundleIdPrefix: com.objp.chai
  deploymentTarget:
    iOS: 18
settings:
  base:
    GENERATE_INFOPLIST_FILE: true

targets:
  Chai:
    type: application
    platform: iOS
    sources: [Chai]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.objp.chai.Chai
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: ${CHAI_TEAM_ID}
        Release:
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: ${CHAI_TEAM_ID}
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "match AdHoc com.objp.chai.Chai"
  ChaiTests:
    type: bundle.unit-test
    platform: iOS
    sources: [ChaiTests]
    dependencies:
      - target: Chai
